// export const MAIN_DATA_LOADED = 'MAIN_DATA_LOADED';
// export const MAIN_DATA_LOAD_FAILED = 'MAIN_DATA_LOADED_FAILED';

// export const BOOTCAMP_DATA_LOADED = 'BOOTCAMP_DATA_LOADED';
// export const BOOTCAMP_DATA_LOAD_FAILED = 'BOOTCAMP_DATA_LOAD_FAILED';

// export const REVIEW_POSTED = 'REVIEW_POSTED';
// export const REVIEW_POST_FAILED= 'REVIEW_POST_FAILED';